---
- name: In-Memory inventory playbook
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fetch Instance Info
      os_server_facts:
        cloud: openstack
      register: result

    - name: Debug
      debug:
        msg: "{{ result }}"

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{ result.ansible_facts.openstack_servers }}"

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.deployment_name }}"
      with_items: "{{ result.ansible_facts.openstack_servers }}"
